script: zip -a test.zip README.md
deploy:
  provider: releases
  api_key:
    secure: Lhv9lOJ7jqbUtL79wQV7FX9fgvcJxX4s1/9DM9dHEcx3E8KdwOPEYGWrFqkhkxnJJHbdH/bu37cXi5/tXfH/HJrhrkfDuuQ0WdcKWl+/TUUzVqnqGskkHJ0BQcnG8m/mG8ZK1U77NGok359vJodJXBXR8zxuqFt+UNMGXjZr35U=
  file: test.zip
  on:
  	tags: true
    repo: mapio/test-travis-release
    all_branches: true
